on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
      - name: Install tools
        run: dotnet tool restore
      - name: Install wasi-experimental
        run: dotnet workload install wasi-experimental
      - name: Install wasi-sdk
        run: |
          export WASI_VERSION=21
          export WASI_VERSION_FULL=${WASI_VERSION}.0
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz
          tar xvf wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          export WASI_SDK_PATH=`pwd`/wasi-sdk-${WASI_VERSION_FULL}
          dotnet build
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage;Format=json,lcov,cobertura"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
